object Versions {
    const val appCompat = "1.6.1"
    const val extJunit = "1.1.3"
    const val androidxJunit_version = "1.1.3"
    const val coreKtx = "1.7.0"
    const val coroutinesAndroid = "1.6.0"
    const val coroutinesCore = "1.6.0"
    const val constraintLayout = "2.1.4"
    const val coil = "1.3.0"
    const val circleImageView = "3.1.0"
    const val espressoCore = "3.5.1"
    const val fragment = "1.6.0"
    const val glide = "4.12.0"
    const val glideCompiler = "4.12.0"
    const val glideTransformationVersion = "4.12.0"
    const val glideAnnotationProcessor = "1.6.0"
    const val gson = "2.9.0"
    const val kotlinxSerialization = "1.4.1"
    const val kotlinVersion = "1.8.20"
    const val koinCore = "2.2.3"
    const val koinAndroid = "2.2.3"
    const val koinScope = "2.2.3"
    const val koinViewModel = "2.2.3"
    const val material = "1.8.0"
    const val retrofit = "2.9.0"
    const val retrofitGsonConverter = "2.9.0"
    const val roomRuntime = "2.5.2"
    const val roomCompiler = "2.5.2"
    const val roomPaging = "2.5.2"
    const val roomCommon = "2.5.2"
    const val roomKtx = "2.4.3"
    const val okhttp = "4.9.1"
    const val okHttpLoggingInterceptor = "4.9.0"
    const val paging = "3.2.1"
    const val pagingRunTimeKtx = "3.2.1"
    const val rxJava2 = "3.1.6"
    const val rxJavaAndroid = "2.1.1"
    const val rxJava2Relev = "2.1.1"
    const val rxJava2Binding = "3.0.0"
    const val swipeRefreshLayout = "1.1.0"
    const val splashScreenCore = "1.0.0"
    const val timber = "5.0.1"

    // Tests Libs
    const val archCoreTest = "1.1.1"
    const val coreTesting = "2.1.0"
    const val coroutinesTest = "1.8.0-RC"
    const val koinTest = "2.2.3"
    const val kotlinTest = "1.7.20"
    const val koinJunit4 = "2.2.3"
    const val mockk = "1.12.1"
    const val mockServerTest = "4.9.0"
    const val testRules_version = "1.3.0"
    const val jUnitVersion = "4.13.2"
    const val junit ="4.12"
    const val junitKtx = "1.1.3"
    const val turbine = "0.8.0"






}
